name: Deploy Backend to AWS App Runner

on:
    push:
        branches:
            - main

env:
    AWS_REGION: us-east-1

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

            - name: 'Create env file'
              run: |
                  echo "${{ secrets.ENV_VARS }}" > .env.production

            - name: Build Docker image
              run: |
                  docker build -t chessio-backend .
                  docker tag chessio-backend:latest 039612890043.dkr.ecr.us-east-1.amazonaws.com/awsxero/chessio-backend:latest

            - name: Push Docker image to Amazon ECR
              run: |
                  docker push 039612890043.dkr.ecr.us-east-1.amazonaws.com/awsxero/chessio-backend:latest

            - name: Wait for App Runner to be ready
              run: |
                  while [[ $(aws apprunner describe-service --service-arn arn:aws:apprunner:us-east-1:039612890043:service/chessio-backend/3f79897fb9f645b681be593f1980507b --query "Service.Status" --output text) == "OPERATION_IN_PROGRESS" ]]; do
                    echo "Waiting for App Runner to be ready..."
                    sleep 30
                  done

            - name: Update App Runner service
              env:
                  AWS_REGION: us-east-1
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws apprunner update-service --service-arn arn:aws:apprunner:us-east-1:039612890043:service/chessio-backend/3f79897fb9f645b681be593f1980507b --source-configuration '{
                    "ImageRepository": {
                      "ImageIdentifier": "039612890043.dkr.ecr.us-east-1.amazonaws.com/awsxero/chessio-backend:latest",
                      "ImageRepositoryType": "ECR"
                    }
                  }'
